<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25669" started-at="2021-03-11T15:24:03 IST" finished-at="2021-03-11T15:24:29 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25669" started-at="2021-03-11T15:24:03 IST" finished-at="2021-03-11T15:24:29 IST">
      <class name="testCase.Login.AdduserTest">
        <test-method status="FAIL" signature="AddEmloyee()[pri:1, instance:testCase.Login.AdduserTest@68e5eea7]" name="AddEmloyee" duration-ms="15" started-at="2021-03-11T15:24:19 IST" finished-at="2021-03-11T15:24:19 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at testCase.Login.AdduserTest.AddEmloyee(AdduserTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddEmloyee -->
      </class> <!-- testCase.Login.AdduserTest -->
      <class name="testCase.Login.LoginTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testCase.Login.LoginTest@671a5887]" name="beforeTest" is-config="true" duration-ms="15987" started-at="2021-03-11T15:24:03 IST" finished-at="2021-03-11T15:24:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="verifyLoginWithCreadentials()[pri:1, instance:testCase.Login.LoginTest@671a5887]" name="verifyLoginWithCreadentials" duration-ms="9525" started-at="2021-03-11T15:24:19 IST" finished-at="2021-03-11T15:24:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithCreadentials -->
      </class> <!-- testCase.Login.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
